package com.antivirus.agent;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.Properties;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DomainSyncTaskTest {

    private Connection connection;
    private Path hostsFile;
    private Path dnsmasqConf;
    private AtomicInteger dnsmasqReloadCount;

    @BeforeEach
    void setUp(@TempDir Path tempDir) throws Exception {
        String dbName = "domain_sync_test_" + UUID.randomUUID();
        connection = DriverManager.getConnection("jdbc:h2:mem:" + dbName + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE blocked_domains (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        domain VARCHAR(255) NOT NULL UNIQUE,
                        blocked_at TIMESTAMP NOT NULL,
                        reason VARCHAR(255),
                        is_active BOOLEAN NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE agent_status (
                        id BIGINT DEFAULT 1 PRIMARY KEY CHECK (id = 1),
                        hosts_file_writable BOOLEAN NOT NULL DEFAULT FALSE,
                        dns_config_writable BOOLEAN NOT NULL DEFAULT FALSE,
                        last_heartbeat_at TIMESTAMP NOT NULL,
                        last_sync_at TIMESTAMP,
                        last_sync_error VARCHAR(500)
                    )
                    """);
            statement.execute(
                    "INSERT INTO agent_status (id, hosts_file_writable, dns_config_writable, last_heartbeat_at) " +
                            "VALUES (1, FALSE, FALSE, CURRENT_TIMESTAMP)");
        }

        hostsFile = tempDir.resolve("hosts");
        Files.writeString(hostsFile, "127.0.0.1 localhost\n");
        dnsmasqConf = tempDir.resolve("antivirus-blocked.conf");
        dnsmasqReloadCount = new AtomicInteger();
    }

    @AfterEach
    void tearDown() throws Exception {
        connection.close();
    }

    private void insertDomain(String domain, boolean active) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute("INSERT INTO blocked_domains (domain, blocked_at, is_active) VALUES ('"
                    + domain + "', CURRENT_TIMESTAMP, " + active + ")");
        }
    }

    private DomainSyncTask newTask(boolean dnsEnabled) {
        Properties props = new Properties();
        props.setProperty("dns.blocking.enabled", String.valueOf(dnsEnabled));
        AgentConfig config = AgentConfig.fromProperties(props);
        HostsFileWriter hostsFileWriter = new HostsFileWriter(hostsFile.toString());
        DnsmasqWriter dnsmasqWriter = new DnsmasqWriter(dnsmasqConf.toString(), dnsmasqReloadCount::incrementAndGet);
        return new DomainSyncTask(config, hostsFileWriter, dnsmasqWriter, new AgentStatusReporter());
    }

    @Test
    void runOnce_ShouldWriteOnlyActiveDomainsToHostsFile() throws Exception {
        insertDomain("blocked.example.com", true);
        insertDomain("inactive.example.com", false);

        newTask(false).runOnce(connection);

        List<String> lines = Files.readAllLines(hostsFile);
        assertTrue(lines.contains("127.0.0.1 blocked.example.com # ANTIVIRUS_BLOCKED_DOMAIN"));
        assertFalse(lines.stream().anyMatch(l -> l.contains("inactive.example.com")));
    }

    @Test
    void runOnce_WithDnsDisabled_ShouldNotTouchDnsmasqConfig() throws Exception {
        insertDomain("blocked.example.com", true);

        newTask(false).runOnce(connection);

        assertFalse(Files.exists(dnsmasqConf), "dnsmasq config should not be created when DNS blocking is disabled");
        assertEquals(0, dnsmasqReloadCount.get());
    }

    @Test
    void runOnce_WithDnsEnabled_ShouldWriteDnsmasqConfigAndReload() throws Exception {
        insertDomain("blocked.example.com", true);

        newTask(true).runOnce(connection);

        assertTrue(Files.exists(dnsmasqConf));
        assertEquals("address=/blocked.example.com/0.0.0.0\n", Files.readString(dnsmasqConf));
        assertEquals(1, dnsmasqReloadCount.get());
    }

    @Test
    void runOnce_SecondCycleWithNoChanges_ShouldSkipRewritingFiles() throws Exception {
        insertDomain("blocked.example.com", true);
        DomainSyncTask task = newTask(true);

        task.runOnce(connection);
        assertEquals(1, dnsmasqReloadCount.get());

        // Touch the hosts file's mtime-sensitive content by re-running with
        // no DB change at all, the writer must not fire again.
        task.runOnce(connection);
        assertEquals(1, dnsmasqReloadCount.get(),
                "a second cycle with an unchanged domain set must not trigger another dnsmasq reload");
    }

    @Test
    void runOnce_WhenDomainSetChanges_ShouldRewriteOnTheNextCycle() throws Exception {
        insertDomain("first.example.com", true);
        DomainSyncTask task = newTask(true);
        task.runOnce(connection);
        assertEquals("address=/first.example.com/0.0.0.0\n", Files.readString(dnsmasqConf));

        insertDomain("second.example.com", true);
        task.runOnce(connection);

        String content = Files.readString(dnsmasqConf);
        assertTrue(content.contains("first.example.com"));
        assertTrue(content.contains("second.example.com"));
        assertEquals(2, dnsmasqReloadCount.get());
    }

    @Test
    void runOnce_ShouldUpdateAgentStatusRow() throws Exception {
        insertDomain("blocked.example.com", true);

        newTask(false).runOnce(connection);

        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("SELECT * FROM agent_status WHERE id = 1")) {
            assertTrue(rs.next());
            assertTrue(rs.getBoolean("hosts_file_writable"));
            assertFalse(rs.getBoolean("dns_config_writable"), "DNS reported not-writable when disabled by config");
        }
    }

    @Test
    void runOnce_WhenHostsFileNotWritable_ShouldSkipWriteAttemptAndReportUnwritable() throws Exception {
        // Parent directory doesn't exist, so isWritable() correctly
        // returns false up front. This is the "probe says no, don't even
        // try" path: no write() call happens, no exception, no
        // last_sync_error, hostsWritable is simply reported false.
        // The write()-throws case (isWritable() said yes, the actual
        // write failed anyway) is covered by DomainSyncTaskTest's own
        // sibling scenario below and by HostsFileWriterTest at the unit
        // level for the writer itself.
        HostsFileWriter unwritableTarget = new HostsFileWriter("/definitely/does/not/exist/hosts");
        DomainSyncTask task = new DomainSyncTask(AgentConfig.fromProperties(new Properties()), unwritableTarget,
                new DnsmasqWriter(dnsmasqConf.toString(), () -> {
                }), new AgentStatusReporter());

        insertDomain("blocked.example.com", true);
        task.runOnce(connection);

        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("SELECT * FROM agent_status WHERE id = 1")) {
            assertTrue(rs.next());
            assertFalse(rs.getBoolean("hosts_file_writable"));
            assertEquals(null, rs.getString("last_sync_error"),
                    "a skipped attempt (probe said unwritable) is not the same as a failed write, no error to report");
        }
    }

    @Test
    void runOnce_WhenHostsFileWriteThrows_ShouldRecordErrorAndRetryOnNextCycle() throws Exception {
        // Make the file exist and pass isWritable(), but not be a regular
        // file writable via Files.write(List), a directory at that path
        // makes the probe say yes (it exists, permission bits allow
        // writing) while the actual write attempt throws.
        Path directoryMasqueradingAsHostsFile = hostsFile.getParent().resolve("hosts-dir");
        Files.createDirectory(directoryMasqueradingAsHostsFile);
        HostsFileWriter brokenWriter = new HostsFileWriter(directoryMasqueradingAsHostsFile.toString());
        DomainSyncTask task = new DomainSyncTask(AgentConfig.fromProperties(new Properties()), brokenWriter,
                new DnsmasqWriter(dnsmasqConf.toString(), () -> {
                }), new AgentStatusReporter());

        insertDomain("blocked.example.com", true);
        task.runOnce(connection);

        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("SELECT * FROM agent_status WHERE id = 1")) {
            assertTrue(rs.next());
            assertFalse(rs.getBoolean("hosts_file_writable"));
            assertTrue(rs.getString("last_sync_error").contains("hosts file write failed"));
        }

        // Next cycle should retry (lastAppliedDomains was never advanced
        // on failure), same broken target still errors the same way,
        // this just confirms it doesn't silently stop trying.
        task.runOnce(connection);
        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("SELECT * FROM agent_status WHERE id = 1")) {
            assertTrue(rs.next());
            assertTrue(rs.getString("last_sync_error").contains("hosts file write failed"));
        }
    }
}
