-- V1__initial_schema.sql
-- Initial schema dump from dev H2 for Flyway to manage in production.
--
-- id uses the ANSI SQL:2003 identity-column syntax (GENERATED ... AS
-- IDENTITY), not AUTO_INCREMENT. AUTO_INCREMENT is H2/MySQL-specific and is
-- rejected outright by H2's MODE=PostgreSQL parser (used by every DB URL
-- in this project, dev/local/prod alike), since real PostgreSQL has never
-- supported it. GENERATED ... AS IDENTITY is standard SQL, supported by
-- both real PostgreSQL and H2, so this migration actually runs on both
-- rather than only ever being reverse-engineered from a Hibernate-managed
-- dev schema that never went through Flyway at all.
CREATE TABLE scan_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path VARCHAR(255) NOT NULL,
    owner_username VARCHAR(255),
    threat_type VARCHAR(255) NOT NULL,
    infected BOOLEAN NOT NULL,
    threat_details VARCHAR(255),
    scan_date_time TIMESTAMP NOT NULL,
    scan_type VARCHAR(255) NOT NULL,
    action_taken VARCHAR(255)
);