-- V2__add_users_table.sql
-- Creates the app_users table for DB-backed authentication.
-- scan_results.owner_username already exists from V1 — no change needed there.
-- See V1 for why id uses GENERATED ... AS IDENTITY instead of AUTO_INCREMENT.
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);