-- V6__add_blocked_domains_table.sql
-- blocked_domains has existed only as a JPA entity (BlockedDomain.java)
-- since this table was introduced, never as a Flyway migration. That was
-- invisible under dev (ddl-auto=update auto-creates it from the entity
-- every startup) but is a real gap under local/prod, both of which use
-- ddl-auto=none with no auto-DDL at all. Discovered when the local
-- profile's scheduled domain-blocking sync crashed with
-- "Table BLOCKED_DOMAINS not found" against a Flyway-only-managed schema,
-- which is exactly what a real prod deployment (spring.flyway.enabled=true,
-- ddl-auto=none) would also hit.
--
-- Column shape matches BlockedDomain.java exactly: id uses the same
-- GENERATED ... AS IDENTITY pattern as V1/V2 (see V1 for why, not
-- AUTO_INCREMENT), domain is unique + not null, blocked_at/is_active are
-- not null per their @Column annotations, reason has no constraints.
-- is_active has no DB-level DEFAULT because Hibernate's own schema
-- generation doesn't emit one for a plain Java field initializer either
-- (would need @ColumnDefault on the entity for that) — the entity always
-- supplies the value on insert regardless, so this matches actual
-- Hibernate-generated behavior rather than adding an untested divergence.
CREATE TABLE blocked_domains (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain      VARCHAR(255) NOT NULL UNIQUE,
    blocked_at  TIMESTAMP NOT NULL,
    reason      VARCHAR(255),
    is_active   BOOLEAN NOT NULL
);
