-- V7__add_network_scan_tables.sql
-- Same gap as V6, network_scan_results, network_vulnerabilities, and the
-- two @ElementCollection tables backing NetworkScanResult
-- (open_ports, suspicious_connections) have only ever existed via
-- ddl-auto=update. Found by proactively checking every @Entity against
-- migration coverage after V6 surfaced the same pattern for
-- blocked_domains; nothing has actually exercised this feature during our
-- testing yet, so this hasn't crashed anything visibly, but it's the
-- identical gap and would fail the same way.
--
-- Column names follow Spring Boot's default physical naming strategy
-- (camelCase Java fields -> snake_case columns): scanTime -> scan_time,
-- firewallEnabled -> firewall_enabled, webProtectionEnabled ->
-- web_protection_enabled, activeThreats -> active_threats,
-- blockedAttempts -> blocked_attempts. int/boolean are Java primitives, so
-- they're NOT NULL (can't hold null); LocalDateTime/String are object
-- types with no @Column(nullable=false), so they're nullable, matching
-- what Hibernate itself would generate for these exact field types.
CREATE TABLE network_scan_results (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    threats                   INT NOT NULL,
    scan_time                 TIMESTAMP,
    status                    VARCHAR(255),
    firewall_enabled          BOOLEAN NOT NULL,
    web_protection_enabled    BOOLEAN NOT NULL,
    active_threats            INT NOT NULL,
    blocked_attempts          INT NOT NULL
);

-- network_vulnerabilities is the "many" side of NetworkScanResult's
-- unidirectional @OneToMany (@JoinColumn(name = "scan_result_id") lives
-- here, not on network_scan_results). Nullable: a NetworkVulnerability
-- isn't required to belong to a scan result at the schema level, matching
-- the entity, which has no nullable=false on that relationship.
CREATE TABLE network_vulnerabilities (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type              VARCHAR(255),
    description       VARCHAR(255),
    severity          VARCHAR(255),
    recommendation    VARCHAR(255),
    scan_result_id    BIGINT,
    CONSTRAINT fk_network_vulnerabilities_scan_result
        FOREIGN KEY (scan_result_id) REFERENCES network_scan_results (id)
);

-- @ElementCollection tables: plain (join column, element value) pairs,
-- no synthetic primary key, matching Hibernate's default DDL generation
-- for element collections (no @OrderColumn or explicit key configured on
-- either field).
CREATE TABLE open_ports (
    scan_result_id    BIGINT NOT NULL,
    port              VARCHAR(255),
    CONSTRAINT fk_open_ports_scan_result
        FOREIGN KEY (scan_result_id) REFERENCES network_scan_results (id)
);

CREATE TABLE suspicious_connections (
    scan_result_id    BIGINT NOT NULL,
    connection        VARCHAR(255),
    CONSTRAINT fk_suspicious_connections_scan_result
        FOREIGN KEY (scan_result_id) REFERENCES network_scan_results (id)
);
