name: system-agent CI test With Maven
on:
    push:
        branches: ["**"]
        paths:
            - "system-agent/**"
            - ".github/workflows/test_system_agent.yml"
    pull_request:
        branches: ["main"]
        paths:
            - "system-agent/**"
            - ".github/workflows/test_system_agent.yml"

jobs:
    test_system_agent:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "21"
                  cache: "maven"
                  cache-dependency-path: "system-agent/pom.xml"

            - name: Run tests with Maven
              working-directory: system-agent
              run: mvn test

            - name: Build runnable jar
              working-directory: system-agent
              run: mvn package -DskipTests
